const getInitiatedLoansByDefaultQuery =
'\
    SELECT cl.* FROM COLLATERALIZED_LOAN cl \
    INNER JOIN \
    COLLATERALIZED_LOAN_STATUS cls \
    ON cl.LOAN_STATUS_CODE = cls.LOAN_STATUS_CODE \
    WHERE cls.LOAN_STATUS_DESC = \'LoanInitiated\' \
    AND cl.LENDER <> $1 \
    ORDER BY cl.LAST_UPDATE_TIME DESC \
    LIMIT 100 \
';

const getLoanDetailsQuery = 
'\
    SELECT cl.* FROM COLLATERALIZED_LOAN cl \
    INNER JOIN \
    COLLATERALIZED_LOAN_STATUS cls \
    ON cl.LOAN_STATUS_CODE = cls.LOAN_STATUS_CODE \
    WHERE cls.LOAN_STATUS_DESC = \'LoanInitiated\' \
    AND cl.LOAN_ID = $1 \
    AND cl.LENDER = $2 \
    ORDER BY cl.LAST_UPDATE_TIME DESC \
';

const getInitiatedLoansByFilterQuery =
'\
    SELECT cl.* FROM COLLATERALIZED_LOAN cl \
    INNER JOIN \
    COLLATERALIZED_LOAN_STATUS cls \
    ON cl.LOAN_STATUS_CODE = cls.LOAN_STATUS_CODE \
    WHERE cls.LOAN_STATUS_DESC = \'LoanInitiated\' \
    AND cl.LENDER <> $1 \
    $$PARAM_SQL$$ \
    ORDER BY cl.LAST_UPDATE_TIME DESC \
    LIMIT 100 \
';

let getLoanLiquidationQuery =
' \
    SELECT cl.LOAN_ID FROM COLLATERALIZED_LOAN cl \
    INNER JOIN \
    COLLATERALIZED_LOAN_STATUS cls \
    ON cl.LOAN_STATUS_CODE = cls.LOAN_STATUS_CODE \
    WHERE cls.LOAN_STATUS_DESC = \'LoanRepaying\' \
    AND cl.LOAN_AMOUNT / (cl.COLLATERAL_AMOUNT * $1) >= (CAST(cl.LIQUIDATION_LTV AS FLOAT) / 100)\
';

let createInitiatedLoanQuery =
' \
    INSERT INTO COLLATERALIZED_LOAN \
    (LOAN_ID, LOAN_AMOUNT, COLLATERAL_AMOUNT, LENDER, LOAN_STATUS_CODE, LOAN_TERM, APR, REPAYMENT_SCHEDULE, MONTHLY_REPAYMENT_AMOUNT, REMAINING_REPAYMENT_COUNT, INITIAL_LTV, MARGIN_LTV, LIQUIDATION_LTV, CREATE_TIME, LAST_UPDATE_TIME) \
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, TO_TIMESTAMP($14), TO_TIMESTAMP($15)) \
';

let updateLoanRequestedQuery =
' \
    UPDATE COLLATERALIZED_LOAN cl \
    SET LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanRequested\'), \
    BORROWER = $1, \
    LAST_UPDATE_TIME = TO_TIMESTAMP($2) \
    WHERE cl.LOAN_ID = $3 \
    AND cl.LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanInitiated\') \
';

let updateLoanCancelledQuery =
' \
    UPDATE COLLATERALIZED_LOAN cl \
    SET LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanCancelled\'), \
    LAST_UPDATE_TIME = TO_TIMESTAMP($1) \
    WHERE cl.LOAN_ID = $2 \
    AND cl.LENDER = $3 \
    AND cl.LOAN_STATUS_CODE <= (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanRequested\') \
';

let updateLoanDisbursedQuery =
' \
    UPDATE COLLATERALIZED_LOAN cl \
    SET LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanRepaying\'), \
    NEXT_REPAYMENT_DEADLINE = TO_TIMESTAMP($1), \
    LAST_UPDATE_TIME = TO_TIMESTAMP($2) \
    WHERE cl.LOAN_ID = $3 \
    AND cl.LENDER = $4 \
    AND cl.LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanRequested\') \
';

let updateLoanRepaidQuery =
' \
    UPDATE COLLATERALIZED_LOAN cl \
    SET REMAINING_REPAYMENT_COUNT = REMAINING_REPAYMENT_COUNT - 1, \
    LAST_UPDATE_TIME = TO_TIMESTAMP($1) \
    WHERE cl.LOAN_ID = $2 \
    AND cl.LENDER = $3 \
    AND cl.LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanRepaying\') \
';

let updateLoanDefaultedQuery =
' \
    UPDATE COLLATERALIZED_LOAN cl \
    SET LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanDefaulted\'), \
    NEXT_REPAYMENT_DEADLINE = NULL, \
    LAST_UPDATE_TIME = TO_TIMESTAMP($1) \
    WHERE cl.LOAN_ID = $2 \
    AND cl.LENDER = $3 \
    AND cl.LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanRepaying\') \
';

let updateLoanFullyRepaidQuery =
' \
    UPDATE COLLATERALIZED_LOAN cl \
    SET LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanCompleted\'), \
    REMAINING_REPAYMENT_COUNT = REMAINING_REPAYMENT_COUNT - 1, \
    NEXT_REPAYMENT_DEADLINE = NULL, \
    LAST_UPDATE_TIME = TO_TIMESTAMP($1) \
    WHERE cl.LOAN_ID = $2 \
    AND cl.BORROWER = $3 \
    AND cl.LOAN_STATUS_CODE = (SELECT LOAN_STATUS_CODE FROM COLLATERALIZED_LOAN_STATUS WHERE LOAN_STATUS_DESC = \'LoanRepaying\') \
';

export {
    getInitiatedLoansByDefaultQuery,
    getLoanDetailsQuery,
    getInitiatedLoansByFilterQuery,
    getLoanLiquidationQuery,
    createInitiatedLoanQuery,
    updateLoanRequestedQuery,
    updateLoanCancelledQuery,
    updateLoanDisbursedQuery,
    updateLoanRepaidQuery,
    updateLoanDefaultedQuery,
    updateLoanFullyRepaidQuery
}